---

- name: Check if yarn is installed
  shell: dpkg-query -l yarn
  ignore_errors: yes
  register: dpkg_yarn_check

- name: Ensure that Yarn is installed
  apt:  name=yarn update_cache=yes
  when: dpkg_yarn_check|failed

- name: Prepare Statsd directory
  file: state=directory path={{statsd_home}}

- name: Prepare Statsd package.json
  template: src=package.json dest={{statsd_home}}/package.json

- name: Install statsd
  yarn: name=statsd path={{statsd_home}}

- name: Install extra NPM dependencies
  yarn: name={{item}} path={{statsd_home}}
  with_items: "{{ statsd_extra_dependencies }}"

- name: Create node user
  user: name={{statsd_user}} state=present shell=/bin/false system=yes

- name: Configure upstart
  template: src=upstart.conf.j2 dest=/etc/init/{{statsd_title}}.conf
  when: ansible_distribution=="Ubuntu" and ansible_distribution_major_version < "15.04"
  notify:
  - "{{statsd_title}} restart"

- name: Configure systemd
  template: src=systemd.service.j2 dest=/etc/systemd/system/{{statsd_title}}.service
  when: ansible_distribution=="Ubuntu" and ansible_distribution_major_version > "15.04"
  notify:
  - "{{statsd_title}} restart"


- name: Configure sysvinit
  template: src=sysvinit.conf.j2 dest=/etc/init.d/{{statsd_title}}
  when: ansible_distribution=="Debian" and ansible_distribution_major_version < 8
  notify:
  - "{{statsd_title}} restart"

- name: Configure systemd
  template: src=systemd.service.j2 dest=/etc/systemd/system/{{statsd_title}}.service
  when: ansible_distribution=="Debian" and ansible_distribution_major_version > 8
  notify:
  - "{{statsd_title}} restart"

- name: Configure statsd
  template: src=statsd.js.j2 dest={{statsd_home}}/config.js
  notify:
  - "{{statsd_title}} restart"

- name: Ensure that Statsd is started
  service: name={{statsd_title}} state=started enabled=yes
